### PR TITLE
Vmc 265 multiple tab

### PR DESCRIPTION
**Pull request by deerwalk**

### CODE REVIEW

**Comment by akhanzode** [comment]
Can the query result span both table and query window like 2 panes on top and result at bottom?
Will this have impact on GEB?

**Comment by akhanzode** [comment]
Height of + can be more maybe compute tab height - margin.

**Comment by deerwalk** [comment]
As per our new design, we have multiple query tabs. Here for each tab, we have the "Query Box" to write the queries and "Query Result" where result of our queries are displayed. Now since "Query Box" and "Query Result" are related to each other and they belong to the specific tab. It would be nice to show them in same level as we are doing right now. If we apply the previous design, then the "Query Box" and "Query Result" will not look like related to each other. 

Similar kind of layout has been used in other database management tools for MS Sql, mySql etc. Also our previous voltdb studio had same kind of layout. 

So we think, it  would be better to use our current design.

**Comment by akhanzode** [comment]
Can you at least make left pane proportionally smaller on larger screen the table/view pane is too big. I am concerned that query result will have scrolling effect when there are > 10 columns to show.

**Comment by deerwalk** [comment]
We will try to make the left panel proportionally smaller so that the table/view pane is not shown too big on a larger screen.

**Pull request merged**
