### PR TITLE
Vmc 315

### PR DESCRIPTION
**Pull request by prabeam**

### CODE REVIEW

**Comment by akhanzode** [comment]
You should use output directory same as java classes where same name files can be minified. This way you dont have to create -min version files. You can possibly use yui compressor as ant task instead of creating a shell script.

**Comment by prabeam** [comment]
We made the required changes as per your comments. We have taken out the js-min folder and used the output directory js to store minified js with same file name as their original one.

**Comment by akhanzode** [comment]
yui jar can be moved to third_party/java/jars as opposed to lib as we dont need it to ship.

**Comment by akhanzode** [comment]
Looks good to me. Please merge to your master after resolving conflicts.

**Pull request merged**
