### PR TITLE
Vmc 358

### PR DESCRIPTION
**Pull request by prabeam**

### CODE REVIEW

**Comment by akhanzode** [comment]
Can you remove/hide the sub-tab thats work in progress?

**Comment by akhanzode** [comment]
For proceduredetails you should look at <ALL> STATEMENT column that will give you overall stats for procedure. For MP there will be 16383 partition id and for SP it will include all partitions (including replicas) their AVG will give you time. The statements inside procedures can be skipped now but can be used for drill down analysis. The times and invocations can be used to chart the analysis data.

**Comment by akhanzode** [comment]
I am not reviewing this and I think -modified is the branch we will review and merge right? If so close this pull request.

**Comment by deerwalk** [comment]
Yes Anish, VMC-358- modified is the branch we will merge after review. We will close this pull request.

**Pull request closed without merging**
